### ISSUE TITLE
Windows Basic is subject to Firefox's Windows 10 button-size butchering

### ISSUE THREAD

**Issue by dominichayesferen** [NetworkNeighborhood/Marble-legacy#2]
![image](https://github.com/user-attachments/assets/824c2f90-ba9a-4ca1-a130-f5a3872eb66b)

yeah - Windows 7-spoofed Firefox for comparison... doesn't butcher the button sizes... for once, curiously.

**Comment by Erizur** [comment]
Marble has no support for older operative systems, probably this applies to compatibility mode as well? I can't seem to know whats the problem here really

**Comment by dominichayesferen** [comment]
> Marble has no support for older operative systems, probably this applies to compatibility mode as well? I can't seem to know whats the problem here really

This is just Windows 10 with Basic forced via Windhawk mods (Taskbar is Ex7's simultaneously forced to be Windows Basic due to that)

**Comment by Erizur** [comment]
you could try forcing dwm to report as off using the about:config flag. search it under widget.native-controls.force-dwm-report-off.
